In [1]:
import numpy as np

In [5]:
# np.eye returns a 2-D array with ones on the diagonal and zeros elsewhere.
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [7]:
a = np.random.randint(low=-3, high=25, size=(3, 7))
a

array([[ 5,  0,  4, 16, 21, 14, 20],
       [ 2, 11, -1,  8, 19, 14, 23],
       [ 0, 12,  5,  2, 10, 20, 14]])

In [8]:
a[0, 3]

np.int64(16)

In [10]:
a[:, 2]

array([ 4, -1,  5])

In [12]:
# Access every second column starting from column 0
a[:, ::2]

array([[ 5,  4, 21, 20],
       [ 2, -1, 19, 23],
       [ 0,  5, 10, 14]])

In [14]:
a.max(axis=0)    # max element in each column

array([ 5, 12,  5, 16, 21, 20, 23])

In [15]:
a.max(axis=1)

array([21, 23, 20])

In [16]:
a.sum(axis=0)

array([ 7, 23,  8, 26, 50, 48, 57])

In [19]:
a = np.array([1, 2, 3, 4])
b = np.zeros(4)

np.concatenate((a, b, np.array([4, 3, 2, 1])))    # np.concatenate takes a tuple of arrays

array([1., 2., 3., 4., 0., 0., 0., 0., 4., 3., 2., 1.])